# 服务器配置
server:
  port: 8080
  host: "0.0.0.0"

# 对话服务配置
conversation:
  max_rounds: 5
  keyword_threshold: 0.3
  embedding_top_k: 10
  vector_threshold: 0.5
  rerank_threshold: 0.7
  rerank_top_k: 5
  fallback_strategy: "fixed"
  fallback_response: "抱歉，我无法回答这个问题。"
  enable_rewrite: true
  enable_rerank: true

# 模型服务配置（使用环境变量）
models:
  # 大语言模型配置
  - type: "chat"
    source: "openai"
    model_name: "deepseek-r1-0528-qwen3-8b"
    parameters:
      base_url: "${GPUSTACK_BASE_URL}"
      api_key: "${GPUSTACK_API_KEY}"
      temperature: 0.7
      max_tokens: 2048
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0

  # 嵌入模型配置
  - type: "embedding"
    source: "openai"
    model_name: "qwen3-embedding"
    parameters:
      base_url: "${GPUSTACK_BASE_URL}"
      api_key: "${GPUSTACK_API_KEY}"
      dimensions: 2560
      encoding_format: "float"

  # 重排序模型配置
  - type: "rerank"
    source: "openai"
    model_name: "bge-reranker-v2-m3"
    parameters:
      base_url: "${GPUSTACK_BASE_URL}"
      api_key: "${GPUSTACK_API_KEY}"
      top_k: 10
      return_documents: true

# 知识库配置
knowledge_base:
  chunk_size: 512
  chunk_overlap: 50
  split_markers: ["\n\n", "\n", "。"]
  image_processing:
    enable_multimodal: true